server:
  port: 8777
  address: 0.0.0.0
  servlet:
    session:
      persistent: false
      timeout: -1
    context-path:
spring:
  main:
    allow-circular-references: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


#server:
#  port: 8777
#spring:
#  application:
#    name: perevod
#  datasource:
#    url: jdbc:as400://172.16.110.9/SSCISS
#    username: bekho94
#    password: Bekho1994
#    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
#    hikari:
#      connection-test-query: values 1
#  jpa:
#    database-platform: org.hibernate.dialect.DB2400Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
